version: "3.8"

services:
  postgres:
    container_name: rustbackend-db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rustbackend_dev
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: rustbackend-redis
    image: "redis:latest"
    ports:
      - "6370:6379"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
